<a href="https://colab.research.google.com/github/DanielEXT10/AI/blob/main/Data_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extraccion de datos desde un JSON

In [ ]:
# Importamos las librerias
import pandas as pd
import json
import os

In [ ]:

f = open('/content/drive/MyDrive/Colab Notebooks/Proyecto de innovacion/Analytics Results/Results/1649868351556-results.json')

In [ ]:
data =json.load(f)

In [ ]:
data

{'headers': {'tool': 'TeleScope',
  'type': '',
  'code': 'PUP',
  'initTime': '2019-12-21T17:07:53.000Z',
  'dumpTime': '2020-01-07T00:54:09.000Z',
  'version': '2022.1.0',
  'name': 'pmea-3274-jobdump-6nero2020.bin',
  'path': 'C:\\PUP Dumps',
  'partitions': ['pmea-3274-jobdump-6nero2020.bin'],
  'uploadedOn': '2022-04-13T16:45:51.565Z',
  'uploadedBy': 'etirado2@slb.com',
  'timestamp': 1649868351556},
 'calibration': {'calibrate_location': 'MVC',
  'calibrate_time': 1495332689,
  'calibrate_user': 'FLORIA',
  'gamma_sf': 0.75098,
  'gamma_off': 0,
  'wob_sf': 9726,
  'wob_off': 8981,
  'torq_sf': 4929,
  'torq_off': 8985,
  'collarsize': 0,
  'scoeff_num': 11,
  'scoeff_denom': 12000,
  't_coeff1': 0.5,
  't_maxcnts1': 75,
  't_coeff2': 1,
  't_maxcnts2': 125,
  't_coeff3': 1.5,
  't_maxcnts3': 150,
  't_coeff4': 2,
  't_maxcnts4': 175,
  't_coeff5': 10},
 'configuration': {'code': 'PUP',
  'version': 'PUPV14.0C04',
  'build': '',
  'revision': '',
  'dumpTime': 'Tue, 07 Jan 2020 00:54:09 GMT',
  'type': None,
  'collarSize': None,
  'collarSizeUnit': None,
  'dumpTimeTicks': None,
  'useManufacturingCodeForEquipmentMatching': False,
  'toolName': 'TeleScope',
  'toolTypeName': '',
  'job': {'name': '19MED0040',
   'company': 'BORR DRILLING',
   'wellName': 'MULACH 5',
   'fieldName': 'MULACH',
   'county': 'PARAISO',
   'state': 'TABASCO',
   'location': 'MXM',
   'engineer': 'MYusoff',
   'initTime': 'Sat, 21 Dec 2019 17:07:53 GMT',
   'tsVersion': '2019.0.01.131',
   'toolSerialNumber': '3274'},
  'configurationFile': None,
  'toolSerial': 3274,
  'coefficients': {'telem': 3,
   'freq_bps': [6, 0, 0, 28, 0, 0, 0, 0],
   'cur_fsl_no': 0,
   'auto_survey_time': 0,
   'pause_period_time': 276,
   'conn_threshold': 0,
   'g_max': 10003,
   'g_min': 9953,
   'h_max': 13364,
   'h_min': 13164,
   'dip_max': 7352,
   'dip_min': 7245,
   'soc_switch': 0,
   'survey_only': 0,
   'gtf_switch_low': 250,
   'gtf_switch_high': 350,
   'option_control_iab_enable': 0,
   'option_control_delayed_survey': 1,
   'option_control_record_struct': 0,
   'option_control_frame_struct': 0,
   'option_control_rotary_switch': 0,
   'option_control_sleep_mode': 0,
   'option_control_soc_algo': 1,
   'option_control_shk_type': 0,
   'option_control_medium_survey': 0,
   'option_control_rep_crc': 0,
   'option_control_dc_soc': 0,
   'option_control_survey_count': 0,
   'mult_shot': 0,
   'rm_primary': 29,
   'rm_alt1': 0,
   'rm_alt2': 0,
   'fsl_alt1': 0,
   'fsl_alt2': 0,
   'telem_alt1': 0,
   'telem_alt2': 0,
   'freq_alt1': 0,
   'freq_alt2': 0,
   'nbits_sync1': 9,
   'pattern_sync1': 59,
   'nbits_sync2': 9,
   'pattern_sync2': 452,
   'freq_sync2': 0,
   'nbits_presync': 0,
   'pattern_presync': 0,
   'nbits_presync_cpmsk': 9,
   'pattern_presync_cpmsk': 59,
   'nbits_presync_bpsk': 9,
   'pattern_presync_bpsk': 59,
   'nbits_presync_qpsk': 24,
   'pattern_presync_qpsk': 490166,
   'xmitter_power': 0,
   'tool_main_address': 152,
   'collar_rpm': 20,
   'dlk_bit_time': 18,
   'e_dlk_personality': 0,
   'dspa_soc': 0,
   'total_modf_in_all_sets': 1,
   'modf_frames': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
   'modf_frames_set': [0, 0, 0, 0, 0],
   'bha_power_sharing_control': 0,
   'downlink_select_tst_pom_tstx': 0,
   'survey_wait': 0,
   'delayed_survey_wait': 5,
   'health_modf_status': 2,
   'dds_interval': 255,
   'modulator_disabled': 255,
   'collar_id': 255,
   'disable_gamma_dtc': 255,
   'disable_ltb_communication': 255,
   'disable_ltb_power_uphole': 255,
   'disable_ltb_power_downhole': 255}},
 'equipment': [{'name': 'ToolSerial',
   'value': '3274',
   'serial': 'ToolSerialNumber',
   'searchNames': ['TeleScope Electronics', 'TeleScope Electronics High Temp'],
   'searchValue': '3274',
   'searchType': 'COMPONENT',
   'fcsn': 'PMEA-CA.3274',
   'matchStatus': 'Matched',
   'edited': False}],
 'runs': [{'runNumber': '19MED0040-2',
   'client': 'BORR DRILLING',
   'country': None,
   'dateIn': '2019-12-23T20:30:00',
   'dateOut': '2019-12-28T11:00:00',
   'drillingDistance': 910,
   'drillingDistanceUnit': 'm',
   'pumpingTime': 239400,
   'pumpingTimeUnit': 's',
   'rentalJob': False,
   'mudType': 'Sea Water',
   'mudDensity': 1200,
   'outOfSpec': False,
   'outOfSpecReason': 'OK',
   'brtDuration': 397800,
   'maxFLWI': 0.059366666666666665,
   'maxDLS': 0.0008088,
   'mudFunnelViscosity': 58,
   'mudPlasticViscosity': 0.018,
   'mudChlorides': 29965.8,
   'mudpH': 9,
   'mudSandVolumeFraction': 0.11,
   'mudSolidVolumeFraction': 0.13,
   'BHPressure': 13686147.053839255,
   'MaxBHTemperature': 317.15,
   'TelemetryBitRate': 3,
   'TelemetryFrequency': 10.5,
   'TelemetryMode': 'QPSKÂ\xa010.5 Hz / 3 bps'}],
 'toolset': [{'toolsetId': 3685878,
   'equipmentId': 1626238,
   'fcsn': 'MDI-CA.4060',
   'module': 'MDI Assembly',
   'component': 'D&I Chassis Low Temp Sextant Mag',
   'description': 'MDI-CA, D&I CHASSIS LOW TEMP, SEXTANT MAG.',
   'toolsetLevel': 2,
   'id': 71292185,
   'parentId': 71292169,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 968658,
   'fcsn': 'MEH-BA.3274',
   'module': 'Electronic Housing',
   'component': 'Electronics Housing',
   'description': 'M10 ELECTRONICS CARTRIDGE HOUSING FOR MEC-BA',
   'toolsetLevel': 2,
   'id': 71292173,
   'parentId': 71292169,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 2888515,
   'fcsn': 'MMA-BE.7088',
   'module': 'Modulator Assembly',
   'component': 'Modulator Assembly',
   'description': 'MMA-BE, M10 MODULATOR ASSY W/DUAL OIL LEVEL SENSOR',
   'toolsetLevel': 1,
   'id': 71292192,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1502878,
   'fcsn': 'MTA-BE.3875',
   'module': 'Turbine Assembly',
   'component': 'Turbine Assembly',
   'description': 'MTA-BG, M10 TURBINE ASSY W/DUAL OIL LEVEL SENSOR',
   'toolsetLevel': 1,
   'id': 71292202,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 1570954,
   'fcsn': 'DEXM-AA.078',
   'module': 'Adhoc',
   'component': 'Dummy Extenders',
   'description': 'POWERPULSE DUMMY EXTENDER WITH FILTER',
   'toolsetLevel': 1,
   'id': 71292211,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 1626239,
   'fcsn': 'E058293.12289',
   'module': 'X-Axis Accelerometer',
   'component': 'PowerPulse/DMM Electronics',
   'description': 'ACCELEROMETER, 160 DEG C',
   'toolsetLevel': 3,
   'id': 71292186,
   'parentId': 71292185,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 1626240,
   'fcsn': 'E058293.12290',
   'module': 'Y-Axis Accelerometer',
   'component': 'PowerPulse/DMM Electronics',
   'description': 'ACCELEROMETER, 160 DEG C',
   'toolsetLevel': 3,
   'id': 71292187,
   'parentId': 71292185,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 1626241,
   'fcsn': 'E058293.12291',
   'module': 'Z-Axis Accelerometer',
   'component': 'PowerPulse/DMM Electronics',
   'description': 'ACCELEROMETER, 160 DEG C',
   'toolsetLevel': 3,
   'id': 71292188,
   'parentId': 71292185,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 2750165,
   'fcsn': 'H350950.23035',
   'module': 'RTC Battery',
   'component': 'LWD RTC Battery',
   'description': 'ASSY, BATTERY 150C RTC',
   'toolsetLevel': 3,
   'id': 71292191,
   'parentId': 71292171,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1851016,
   'fcsn': 'MEXD-BA.14/072',
   'module': 'Adhoc',
   'component': 'MWD Female Extender',
   'description': '*OBS, USE 100019316* MEXD-BA M10 DOWNHOLE EXTENDER',
   'toolsetLevel': 1,
   'id': 71292220,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 2691194,
   'fcsn': 'MSSD-EC.MVCDRL-291018-2',
   'module': 'Adhoc',
   'component': 'MWD Crossover Subs',
   'description': 'MSSD-EC, CROSSOVER SUB, M10, 7-5/  8 REG BOX X 7-5/8 H-90 PIN, STAINLESS STEEL',
   'toolsetLevel': 1,
   'id': 71292210,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2958004,
   'fcsn': 'MSSD-FC.SLB-MOL-120719D-06',
   'module': 'Adhoc',
   'component': 'MWD Crossover Subs',
   'description': 'MSSD-FC, CROSSOVER, 7-5/8 H-90 PIN X 7-5/8 H-90 PIN',
   'toolsetLevel': 1,
   'id': 71292221,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 968653,
   'fcsn': 'PMEA-CA.3274',
   'module': 'Electronics',
   'component': 'TeleScope Electronics',
   'description': 'POWER-UP M10  ELECTRONICS ASSEMBLY, 150C',
   'toolsetLevel': 1,
   'id': 71292169,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968654,
   'fcsn': 'PMEC-CA.3274',
   'module': 'Electronic Cartridge',
   'component': 'TeleScope Low Temp Chassis',
   'description': 'ASSEMBLY, POWER-UP M10 ELECTRONICS CHASSIS, 150C',
   'toolsetLevel': 2,
   'id': 71292172,
   'parentId': 71292169,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 690542,
   'fcsn': 'PMVC-AA.225',
   'module': 'MGD/MGR/MVC option',
   'component': 'MVC TeleScope',
   'description': 'PMVC-AA, ASSEMBLY, POWER-UP M10 VIBRATION CHASSIS, 150C',
   'toolsetLevel': 2,
   'id': 71292171,
   'parentId': 71292169,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 1493706,
   'fcsn': 'MDCIX-HA.G2214',
   'module': 'Adhoc',
   'component': 'MDC 950',
   'description': 'MDCIX-HA, 9-1/2 NORMAL FLOW IWOB COLLAR, INT. ALIGN. KEY, BOX x BOX, NO R.O.P.',
   'toolsetLevel': 0,
   'id': 71292168,
   'parentId': None,
   'size': '900/950',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1531540,
   'fcsn': 'MTK_A-DG.021NIIA',
   'module': 'Adhoc',
   'component': 'MOD Kit',
   'description': 'M10 KIT F/5.9 BORE COLLARS, W/BOLT RETAINER MTA HSG, AND INTERNAL ALIGNMENT KEY COLLAR HARDWARE.',
   'toolsetLevel': 1,
   'id': 71292215,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1366155,
   'fcsn': 'S-262553.225_TEMP',
   'module': 'Accelerometer Block Assembly',
   'component': 'PowerPulse/TeleScope',
   'description': 'M10-MVC ACCEL BLOCK ASSEMBLY',
   'toolsetLevel': 3,
   'id': 71292183,
   'parentId': 71292171,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 1626242,
   'fcsn': 'S-262642.4019',
   'module': 'Magnetometer Assy',
   'component': 'PowerPulse/TeleScope',
   'description': 'ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10',
   'toolsetLevel': 3,
   'id': 71292189,
   'parentId': 71292185,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 1932827,
   'fcsn': 'S-266572.MS59-026',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'MODULATOR WEAR SLEEVE ASSY., 5.9, M10',
   'toolsetLevel': 1,
   'id': 71292214,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2895875,
   'fcsn': 'S-266701.8000',
   'module': 'Upper Chassis Assembly',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSY, FIELD COIL UPHOLE M10 ALTERNATOR',
   'toolsetLevel': 2,
   'id': 71292206,
   'parentId': 71292202,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 968669,
   'fcsn': 'S-270540.152334-1',
   'module': 'DOC Board',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT',
   'toolsetLevel': 3,
   'id': 71292177,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968673,
   'fcsn': 'S-270570.152106-3',
   'module': 'Motor Control Board',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, M10 MOTOR CONTROL',
   'toolsetLevel': 3,
   'id': 71292181,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968670,
   'fcsn': 'S-270640.151642-5',
   'module': 'Acquisition Board',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, M10 ACQUISITION',
   'toolsetLevel': 3,
   'id': 71292178,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 1626243,
   'fcsn': 'S-270780.191478-2',
   'module': 'DNI Calibration Board',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, D&I CALIBRATION',
   'toolsetLevel': 3,
   'id': 71292190,
   'parentId': 71292185,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 485826,
   'fcsn': 'S-270910.116233-3',
   'module': 'Vibration Acquisition Board',
   'component': 'TeleScope PWA',
   'description': 'ASSEMBLY, PWB, VIBRATION ACQUISITION',
   'toolsetLevel': 3,
   'id': 71292170,
   'parentId': 71292171,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968674,
   'fcsn': 'S-271007.1110-7',
   'module': 'Triple Transformer',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, TRIPLE TRANSFORMER',
   'toolsetLevel': 3,
   'id': 71292182,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968672,
   'fcsn': 'S-271300.151283-2',
   'module': 'Alternator Control Board',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSEMBLY, M10 ALTERNATOR CONTROL W/HEATSINK',
   'toolsetLevel': 3,
   'id': 71292180,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2895877,
   'fcsn': 'S-274696.7375',
   'module': 'Lower Chassis Assembly',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSY, FIELD COIL DOWNHOLE M10 ALTERNATOR',
   'toolsetLevel': 2,
   'id': 71292207,
   'parentId': 71292202,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2888523,
   'fcsn': 'S-279458.4835',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ROTOR ASSEMBLY, M10 MODULATOR MOTOR',
   'toolsetLevel': 3,
   'id': 71292200,
   'parentId': 71292194,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2822743,
   'fcsn': 'S-279460.700-1400-02',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'WEAR SLEEVE, M10 800-1400 GPM TURBINE',
   'toolsetLevel': 1,
   'id': 71292218,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 1908466,
   'fcsn': 'S-298739.H192657-4',
   'module': 'Adhoc',
   'component': 'Turbine Assembly',
   'description': 'ASSY, MTA M10 TURBINE JUMPER 5.9" ID COLLAR, INCONEL',
   'toolsetLevel': 1,
   'id': 71292219,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2888520,
   'fcsn': 'S-298853.18112',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'MACHINE/COATING DWG. MMA BEARING HSG.',
   'toolsetLevel': 3,
   'id': 71292197,
   'parentId': 71292193,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1262412,
   'fcsn': 'S-298895.714',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSY, END CAP, 5.9"" BORE, M10, UPHOLE',
   'toolsetLevel': 1,
   'id': 71292213,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1835108,
   'fcsn': 'S-298928.3558-MWD',
   'module': 'Pressure Compensator',
   'component': 'Compensator Assembly',
   'description': 'ASSEMBLY, PRESSURE COMPENSATOR W/NEW OIL LEVEL SENSOR, M10 TURBINE',
   'toolsetLevel': 2,
   'id': 71292204,
   'parentId': 71292202,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 2916497,
   'fcsn': '100065811.TS59-048',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'LONG SLEEVE, MACHINE/COATING, MTA 5.9 ID COLLAR',
   'toolsetLevel': 1,
   'id': 71292217,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 2888522,
   'fcsn': '100131285.3098',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'MOTOR ASSEMBLY',
   'toolsetLevel': 3,
   'id': 71292199,
   'parentId': 71292194,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
  {'toolsetId': 3685878,
   'equipmentId': 1420397,
   'fcsn': '100158529.3772',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'SHAFT, M10 TURBINE',
   'toolsetLevel': 2,
   'id': 71292203,
   'parentId': 71292202,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 968668,
   'fcsn': '100162589.151502-5',
   'module': 'Triple Power Supply Board',
   'component': 'PowerPulse/TeleScope',
   'description': 'ASSEMBLY, TRIPLE POWER SUPPLY',
   'toolsetLevel': 3,
   'id': 71292176,
   'parentId': 71292172,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 2895892,
   'fcsn': '100210902.3177',
   'module': 'Rotor',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSY, ROTOR, M10 ALTERNATOR',
   'toolsetLevel': 2,
   'id': 71292208,
   'parentId': 71292202,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MED'},
  {'toolsetId': 3685878,
   'equipmentId': 2016379,
   'fcsn': '100220089.TPS59-52',
   'module': 'Adhoc',
   'component': 'PowerPulse/TeleScope Mechanical',
   'description': 'ASSY, 5.9"" AXIAL LOADING DEVICE, W/OUTER FILTER',
   'toolsetLevel': 1,
   'id': 71292212,
   'parentId': 71292168,
   'size': '',
   'siteHierarchy': None,
   'currentSiteHierarchy': 'OAT-MCA-MSA'},
  {'toolsetId': 3685878,
   'equipmentId': 968667,
   'fcsn': '100515238.151276-1',
   'module': 'UH LTB Power Supply Board',
   'component': 'TeleScope PWA',

In [ ]:
data.keys()

dict_keys(['headers', 'calibration', 'configuration', 'equipment', 'runs', 'toolset', 'results'])

In [ ]:
 toolset =data['toolset']

In [ ]:
toolset

[{'toolsetId': 3685878,
  'equipmentId': 1626238,
  'fcsn': 'MDI-CA.4060',
  'module': 'MDI Assembly',
  'component': 'D&I Chassis Low Temp Sextant Mag',
  'description': 'MDI-CA, D&I CHASSIS LOW TEMP, SEXTANT MAG.',
  'toolsetLevel': 2,
  'id': 71292185,
  'parentId': 71292169,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 968658,
  'fcsn': 'MEH-BA.3274',
  'module': 'Electronic Housing',
  'component': 'Electronics Housing',
  'description': 'M10 ELECTRONICS CARTRIDGE HOUSING FOR MEC-BA',
  'toolsetLevel': 2,
  'id': 71292173,
  'parentId': 71292169,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2888515,
  'fcsn': 'MMA-BE.7088',
  'module': 'Modulator Assembly',
  'component': 'Modulator Assembly',
  'description': 'MMA-BE, M10 MODULATOR ASSY W/DUAL OIL LEVEL SENSOR',
  'toolsetLevel': 1,
  'id': 71292192,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1502878,
  'fcsn': 'MTA-BE.3875',
  'module': 'Turbine Assembly',
  'component': 'Turbine Assembly',
  'description': 'MTA-BG, M10 TURBINE ASSY W/DUAL OIL LEVEL SENSOR',
  'toolsetLevel': 1,
  'id': 71292202,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1570954,
  'fcsn': 'DEXM-AA.078',
  'module': 'Adhoc',
  'component': 'Dummy Extenders',
  'description': 'POWERPULSE DUMMY EXTENDER WITH FILTER',
  'toolsetLevel': 1,
  'id': 71292211,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1626239,
  'fcsn': 'E058293.12289',
  'module': 'X-Axis Accelerometer',
  'component': 'PowerPulse/DMM Electronics',
  'description': 'ACCELEROMETER, 160 DEG C',
  'toolsetLevel': 3,
  'id': 71292186,
  'parentId': 71292185,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 1626240,
  'fcsn': 'E058293.12290',
  'module': 'Y-Axis Accelerometer',
  'component': 'PowerPulse/DMM Electronics',
  'description': 'ACCELEROMETER, 160 DEG C',
  'toolsetLevel': 3,
  'id': 71292187,
  'parentId': 71292185,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 1626241,
  'fcsn': 'E058293.12291',
  'module': 'Z-Axis Accelerometer',
  'component': 'PowerPulse/DMM Electronics',
  'description': 'ACCELEROMETER, 160 DEG C',
  'toolsetLevel': 3,
  'id': 71292188,
  'parentId': 71292185,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 2750165,
  'fcsn': 'H350950.23035',
  'module': 'RTC Battery',
  'component': 'LWD RTC Battery',
  'description': 'ASSY, BATTERY 150C RTC',
  'toolsetLevel': 3,
  'id': 71292191,
  'parentId': 71292171,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1851016,
  'fcsn': 'MEXD-BA.14/072',
  'module': 'Adhoc',
  'component': 'MWD Female Extender',
  'description': '*OBS, USE 100019316* MEXD-BA M10 DOWNHOLE EXTENDER',
  'toolsetLevel': 1,
  'id': 71292220,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2691194,
  'fcsn': 'MSSD-EC.MVCDRL-291018-2',
  'module': 'Adhoc',
  'component': 'MWD Crossover Subs',
  'description': 'MSSD-EC, CROSSOVER SUB, M10, 7-5/  8 REG BOX X 7-5/8 H-90 PIN, STAINLESS STEEL',
  'toolsetLevel': 1,
  'id': 71292210,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2958004,
  'fcsn': 'MSSD-FC.SLB-MOL-120719D-06',
  'module': 'Adhoc',
  'component': 'MWD Crossover Subs',
  'description': 'MSSD-FC, CROSSOVER, 7-5/8 H-90 PIN X 7-5/8 H-90 PIN',
  'toolsetLevel': 1,
  'id': 71292221,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 968653,
  'fcsn': 'PMEA-CA.3274',
  'module': 'Electronics',
  'component': 'TeleScope Electronics',
  'description': 'POWER-UP M10  ELECTRONICS ASSEMBLY, 150C',
  'toolsetLevel': 1,
  'id': 71292169,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968654,
  'fcsn': 'PMEC-CA.3274',
  'module': 'Electronic Cartridge',
  'component': 'TeleScope Low Temp Chassis',
  'description': 'ASSEMBLY, POWER-UP M10 ELECTRONICS CHASSIS, 150C',
  'toolsetLevel': 2,
  'id': 71292172,
  'parentId': 71292169,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 690542,
  'fcsn': 'PMVC-AA.225',
  'module': 'MGD/MGR/MVC option',
  'component': 'MVC TeleScope',
  'description': 'PMVC-AA, ASSEMBLY, POWER-UP M10 VIBRATION CHASSIS, 150C',
  'toolsetLevel': 2,
  'id': 71292171,
  'parentId': 71292169,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1493706,
  'fcsn': 'MDCIX-HA.G2214',
  'module': 'Adhoc',
  'component': 'MDC 950',
  'description': 'MDCIX-HA, 9-1/2 NORMAL FLOW IWOB COLLAR, INT. ALIGN. KEY, BOX x BOX, NO R.O.P.',
  'toolsetLevel': 0,
  'id': 71292168,
  'parentId': None,
  'size': '900/950',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1531540,
  'fcsn': 'MTK_A-DG.021NIIA',
  'module': 'Adhoc',
  'component': 'MOD Kit',
  'description': 'M10 KIT F/5.9 BORE COLLARS, W/BOLT RETAINER MTA HSG, AND INTERNAL ALIGNMENT KEY COLLAR HARDWARE.',
  'toolsetLevel': 1,
  'id': 71292215,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1366155,
  'fcsn': 'S-262553.225_TEMP',
  'module': 'Accelerometer Block Assembly',
  'component': 'PowerPulse/TeleScope',
  'description': 'M10-MVC ACCEL BLOCK ASSEMBLY',
  'toolsetLevel': 3,
  'id': 71292183,
  'parentId': 71292171,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1626242,
  'fcsn': 'S-262642.4019',
  'module': 'Magnetometer Assy',
  'component': 'PowerPulse/TeleScope',
  'description': 'ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10',
  'toolsetLevel': 3,
  'id': 71292189,
  'parentId': 71292185,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 1932827,
  'fcsn': 'S-266572.MS59-026',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'MODULATOR WEAR SLEEVE ASSY., 5.9, M10',
  'toolsetLevel': 1,
  'id': 71292214,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2895875,
  'fcsn': 'S-266701.8000',
  'module': 'Upper Chassis Assembly',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, FIELD COIL UPHOLE M10 ALTERNATOR',
  'toolsetLevel': 2,
  'id': 71292206,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 968669,
  'fcsn': 'S-270540.152334-1',
  'module': 'DOC Board',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT',
  'toolsetLevel': 3,
  'id': 71292177,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968673,
  'fcsn': 'S-270570.152106-3',
  'module': 'Motor Control Board',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, M10 MOTOR CONTROL',
  'toolsetLevel': 3,
  'id': 71292181,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968670,
  'fcsn': 'S-270640.151642-5',
  'module': 'Acquisition Board',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, M10 ACQUISITION',
  'toolsetLevel': 3,
  'id': 71292178,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1626243,
  'fcsn': 'S-270780.191478-2',
  'module': 'DNI Calibration Board',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, D&I CALIBRATION',
  'toolsetLevel': 3,
  'id': 71292190,
  'parentId': 71292185,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 485826,
  'fcsn': 'S-270910.116233-3',
  'module': 'Vibration Acquisition Board',
  'component': 'TeleScope PWA',
  'description': 'ASSEMBLY, PWB, VIBRATION ACQUISITION',
  'toolsetLevel': 3,
  'id': 71292170,
  'parentId': 71292171,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968674,
  'fcsn': 'S-271007.1110-7',
  'module': 'Triple Transformer',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, TRIPLE TRANSFORMER',
  'toolsetLevel': 3,
  'id': 71292182,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968672,
  'fcsn': 'S-271300.151283-2',
  'module': 'Alternator Control Board',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSEMBLY, M10 ALTERNATOR CONTROL W/HEATSINK',
  'toolsetLevel': 3,
  'id': 71292180,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2895877,
  'fcsn': 'S-274696.7375',
  'module': 'Lower Chassis Assembly',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, FIELD COIL DOWNHOLE M10 ALTERNATOR',
  'toolsetLevel': 2,
  'id': 71292207,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888523,
  'fcsn': 'S-279458.4835',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ROTOR ASSEMBLY, M10 MODULATOR MOTOR',
  'toolsetLevel': 3,
  'id': 71292200,
  'parentId': 71292194,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2822743,
  'fcsn': 'S-279460.700-1400-02',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'WEAR SLEEVE, M10 800-1400 GPM TURBINE',
  'toolsetLevel': 1,
  'id': 71292218,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 1908466,
  'fcsn': 'S-298739.H192657-4',
  'module': 'Adhoc',
  'component': 'Turbine Assembly',
  'description': 'ASSY, MTA M10 TURBINE JUMPER 5.9" ID COLLAR, INCONEL',
  'toolsetLevel': 1,
  'id': 71292219,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888520,
  'fcsn': 'S-298853.18112',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'MACHINE/COATING DWG. MMA BEARING HSG.',
  'toolsetLevel': 3,
  'id': 71292197,
  'parentId': 71292193,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1262412,
  'fcsn': 'S-298895.714',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, END CAP, 5.9"" BORE, M10, UPHOLE',
  'toolsetLevel': 1,
  'id': 71292213,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1835108,
  'fcsn': 'S-298928.3558-MWD',
  'module': 'Pressure Compensator',
  'component': 'Compensator Assembly',
  'description': 'ASSEMBLY, PRESSURE COMPENSATOR W/NEW OIL LEVEL SENSOR, M10 TURBINE',
  'toolsetLevel': 2,
  'id': 71292204,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2916497,
  'fcsn': '100065811.TS59-048',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'LONG SLEEVE, MACHINE/COATING, MTA 5.9 ID COLLAR',
  'toolsetLevel': 1,
  'id': 71292217,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2888522,
  'fcsn': '100131285.3098',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'MOTOR ASSEMBLY',
  'toolsetLevel': 3,
  'id': 71292199,
  'parentId': 71292194,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 1420397,
  'fcsn': '100158529.3772',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'SHAFT, M10 TURBINE',
  'toolsetLevel': 2,
  'id': 71292203,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968668,
  'fcsn': '100162589.151502-5',
  'module': 'Triple Power Supply Board',
  'component': 'PowerPulse/TeleScope',
  'description': 'ASSEMBLY, TRIPLE POWER SUPPLY',
  'toolsetLevel': 3,
  'id': 71292176,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2895892,
  'fcsn': '100210902.3177',
  'module': 'Rotor',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, ROTOR, M10 ALTERNATOR',
  'toolsetLevel': 2,
  'id': 71292208,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2016379,
  'fcsn': '100220089.TPS59-52',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, 5.9"" AXIAL LOADING DEVICE, W/OUTER FILTER',
  'toolsetLevel': 1,
  'id': 71292212,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MSA'},
 {'toolsetId': 3685878,
  'equipmentId': 968667,
  'fcsn': '100515238.151276-1',
  'module': 'UH LTB Power Supply Board',
  'component': 'TeleScope PWA',
  'description': 'PWA, TEL101, LTB POWER SUPPLY',
  'toolsetLevel': 3,
  'id': 71292175,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968666,
  'fcsn': '100515238.151276-4',
  'module': 'DH LTB Power Supply Board',
  'component': 'TeleScope PWA',
  'description': 'PWA, TEL101, LTB POWER SUPPLY',
  'toolsetLevel': 3,
  'id': 71292174,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 968671,
  'fcsn': '100522201.151286-3',
  'module': 'Motor Drive Board',
  'component': 'TeleScope PWA',
  'description': 'PWA, TEL102, MOTOR DRIVE',
  'toolsetLevel': 3,
  'id': 71292179,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1564126,
  'fcsn': '100543577.5785410010',
  'module': 'Controller Board',
  'component': 'TeleScope PWA',
  'description': 'PWA, TEL103, WDDHC05',
  'toolsetLevel': 3,
  'id': 71292184,
  'parentId': 71292172,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888524,
  'fcsn': '100629937.CA2029',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'CARRIER, PLANET M10 MOD GEARTRAIN, HEX KEYWAY',
  'toolsetLevel': 3,
  'id': 71292201,
  'parentId': 71292194,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888521,
  'fcsn': '100629942.GD0862',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'MODIFIED HEX, MODULATOR SHAFT',
  'toolsetLevel': 3,
  'id': 71292198,
  'parentId': 71292193,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2895894,
  'fcsn': '100727584.3875',
  'module': 'Housing',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'HOUSING, MTA, FINAL MACHINING, TELESCOPE',
  'toolsetLevel': 2,
  'id': 71292209,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 1674661,
  'fcsn': '100783573.600-1200-58',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ROTOR, MACHINE, M10 600-1200 GPM TURBINE, 0.865 IN COUNTERBORE.',
  'toolsetLevel': 1,
  'id': 71292216,
  'parentId': 71292168,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2337416,
  'fcsn': '100823452.GD0590',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, GEARTRAIN, POWERPULSE MTA W/HEX INPUT GEAR SHAFT',
  'toolsetLevel': 2,
  'id': 71292205,
  'parentId': 71292202,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2888516,
  'fcsn': '100823881.9059329I',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSEMBLY, MMA BEARING HOUSING W/HEX SHAFT',
  'toolsetLevel': 2,
  'id': 71292193,
  'parentId': 71292192,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888517,
  'fcsn': '100823996.9059332H',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, M10 MODULATOR MOTOR & GEARTRAIN W/ HEX PLANET CARRIER',
  'toolsetLevel': 2,
  'id': 71292194,
  'parentId': 71292192,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MVCTLM'},
 {'toolsetId': 3685878,
  'equipmentId': 2888519,
  'fcsn': '101370984.308760-9',
  'module': 'Adhoc',
  'component': 'PowerPulse/TeleScope Mechanical',
  'description': 'ASSY, M10 MODULATOR OIL LEVEL SENSOR ASSEMBLY',
  'toolsetLevel': 3,
  'id': 71292196,
  'parentId': 71292195,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'},
 {'toolsetId': 3685878,
  'equipmentId': 2888518,
  'fcsn': '101535018.9059333F',
  'module': 'Adhoc',
  'component': 'Modulator',
  'description': 'ASSEMBLY, PRESSURE COMPENSATOR W/NEW OIL LEVEL SENSOR, M10 MODULATOR',
  'toolsetLevel': 2,
  'id': 71292195,
  'parentId': 71292192,
  'size': '',
  'siteHierarchy': None,
  'currentSiteHierarchy': 'OAT-MCA-MED'}]

In [ ]:
toolset= [{'fcsn':d['fcsn'],'description': d['description'],'toolsetLevel':d['toolsetLevel'] }for d in toolset if d.get('component') in ['TeleScope PWA','PowerPulse/TeleScope']]
toolset_dict = {
    'toolset':toolset
}

In [ ]:
toolset_dict

{'toolset': [{'fcsn': 'S-262553.225_TEMP',
   'description': 'M10-MVC ACCEL BLOCK ASSEMBLY',
   'toolsetLevel': 3},
  {'fcsn': 'S-262642.4019',
   'description': 'ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10',
   'toolsetLevel': 3},
  {'fcsn': 'S-270540.152334-1',
   'description': 'ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT',
   'toolsetLevel': 3},
  {'fcsn': 'S-270570.152106-3',
   'description': 'ASSEMBLY, M10 MOTOR CONTROL',
   'toolsetLevel': 3},
  {'fcsn': 'S-270640.151642-5',
   'description': 'ASSEMBLY, M10 ACQUISITION',
   'toolsetLevel': 3},
  {'fcsn': 'S-270780.191478-2',
   'description': 'ASSEMBLY, D&I CALIBRATION',
   'toolsetLevel': 3},
  {'fcsn': 'S-270910.116233-3',
   'description': 'ASSEMBLY, PWB, VIBRATION ACQUISITION',
   'toolsetLevel': 3},
  {'fcsn': 'S-271007.1110-7',
   'description': 'ASSEMBLY, TRIPLE TRANSFORMER',
   'toolsetLevel': 3},
  {'fcsn': '100162589.151502-5',
   'description': 'ASSEMBLY, TRIPLE POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100515238.151276-1',
   'description': 'PWA, TEL101, LTB POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100515238.151276-4',
   'description': 'PWA, TEL101, LTB POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100522201.151286-3',
   'description': 'PWA, TEL102, MOTOR DRIVE',
   'toolsetLevel': 3},
  {'fcsn': '100543577.5785410010',
   'description': 'PWA, TEL103, WDDHC05',
   'toolsetLevel': 3}]}

In [ ]:
data['results']

{'runinfo': {'incasing_chart': {'name': 'Incasing Detection Plot',
   'value': 0,
   'unit': '',
   'group': '',
   'isVisible': True},
  'run_number1': {'name': 'Run Number 1',
   'value_string': '19MED0040-2',
   'group': '',
   'isVisible': True},
  'pumping_hours1': {'name': 'Pumping hours1(Qtrac)',
   'value_string': '66.5',
   'group': '',
   'isVisible': True},
  'country': {'name': 'Country',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'electronics': {'name': 'Electronics SN',
   'value_string': 'PMEA-CA.3274',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '1.0',
   'group': '',
   'isVisible': True}},
 'general': {'max_hstemp': {'name': 'Max HSTEMP',
   'value': 47,
   'unit': 'degC',
   'limit': 130,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'max_htemp': {'name': 'Max HTEMP',
   'value': 47,
   'unit': 'degC',
   'limit': 130,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'hs_dev': {'name': 'HSTEMP Temperature Deviation',
   'value': 5,
   'unit': 'degC',
   'limit': 30,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'dni_dev': {'name': 'D&I Temperature Deviation',
   'value': 3,
   'unit': 'degC',
   'limit': 10,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'hstemp_130': {'name': 'Time of HSTEMP > 130 degC',
   'value': 0,
   'unit': 'min',
   'limit': 60,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'hstemp_150': {'name': 'Time of HSTEMP > 150 degC',
   'value': 0,
   'unit': 'min',
   'limit': 5,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'hstemp_175': {'name': 'Time of HSTEMP > 175 degC',
   'value': 0,
   'unit': 'min',
   'limit': 5,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'pumphrs': {'name': 'Pumping Hours',
   'value': 55.73,
   'unit': 'hr',
   'limit': 500,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'time4000': {'name': 'Time at turbine RPM above 4000',
   'value': 0,
   'unit': 'hr',
   'limit': 2,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'pwr_cycle': {'name': 'Total Power Cycle',
   'value': 68,
   'unit': '',
   'group': '',
   'isVisible': True},
  'rpm_ratio': {'name': 'VDC turbine RPM ratio',
   'value': 0.17,
   'unit': '',
   'group': '',
   'isVisible': True},
  'electronic_pmgr': {'name': 'PMGR NOT installed',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'electronic_pmvc': {'name': 'PMVC installed',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'electronic_tapwd': {'name': 'TAPWD NOT installed',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'electronic_iwob': {'name': 'IWOB installed',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '1.0',
   'group': '',
   'isVisible': True}},
 'environmental': {'shk50_g': {'name': 'Total SHK counts above 50G',
   'value': 155,
   'unit': 'cnt',
   'limit': 200000,
   'status': 'Pass',
   'group': 'shock',
   'isVisible': True},
  'sh_krisk3': {'name': 'Time at SHK risk 3',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'shock',
   'isVisible': True},
  'shk_temp': {'name': 'Time above 130C & SHK risk 3',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'shock',
   'isVisible': True},
  'sns_100_100': {'name': 'Cumulative time SnS>100% (CRPM < 100)',
   'value': 0.7455555555555556,
   'unit': 'hr',
   'limit': 24,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'sns_100_150': {'name': 'Cumulative time SnS>150% (CRPM < 100)',
   'value': 0.3388888888888889,
   'unit': 'hr',
   'limit': 1,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'sns_100200_75': {'name': 'Cumulative time SnS>75% (100<= CRPM <=200)',
   'value': 0,
   'unit': 'hr',
   'limit': 24,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'sns_100200_125': {'name': 'Cumulative time SnS>125% (100<= CRPM <=200)',
   'value': 0,
   'unit': 'hr',
   'limit': 1,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'sns_200_50': {'name': 'Cumulative time SnS>50% (CRPM > 200)',
   'value': 0,
   'unit': 'hr',
   'limit': 24,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'sns_200_100': {'name': 'Cumulative time SnS>100% (CRPM > 200)',
   'value': 0,
   'unit': 'hr',
   'limit': 1,
   'status': 'Pass',
   'group': 'stick & slip',
   'isVisible': True},
  'vibx_m': {'name': 'Time at VIBX(gRMS) >4',
   'value': 0,
   'unit': 'hr',
   'limit': 2,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'viby_m': {'name': 'Time at VIBY(gRMS) >4',
   'value': 0,
   'unit': 'hr',
   'limit': 2,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'vibz_m': {'name': 'Time at VIBZ(gRMS) >4',
   'value': 0,
   'unit': 'hr',
   'limit': 2,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'vibl_m': {'name': 'Time at VIB_LAT(gRMS) >4',
   'value': 0.16666666666666666,
   'unit': 'hr',
   'limit': 2,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'vibx_h': {'name': 'Time at VIBX(gRMS) >7',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'viby_h': {'name': 'Time at VIBY(gRMS) >7',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'vibz_h': {'name': 'Time at VIBZ(gRMS) >7',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'vibl_h': {'name': 'Time at VIB_LAT(gRMS) >7',
   'value': 0,
   'unit': 'hr',
   'limit': 0.5,
   'status': 'Pass',
   'group': 'vibration',
   'isVisible': True},
  'peakshock': {'name': 'Max Peak shock ',
   'value': 112,
   'unit': 'G',
   'group': 'shock',
   'isVisible': True},
  'shk25': {'name': 'SHK25 total count',
   'value': 1618,
   'unit': '',
   'group': 'shock',
   'isVisible': True},
  'shk50': {'name': 'SHK50 total count',
   'value': 154,
   'unit': '',
   'group': 'shock',
   'isVisible': True},
  'shk125': {'name': 'SHK125 total count',
   'value': 1,
   'unit': '',
   'group': 'shock',
   'isVisible': True},
  'shk250': {'name': 'SHK250 total count',
   'value': 0,
   'unit': '',
   'group': 'shock',
   'isVisible': True},
  'action_table': {'name': 'Action: service level table',
   'value_string': '',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '2.0',
   'group': '',
   'isVisible': True}},
 'manual': {'message': {'name': 'Manual input',
   'value_string': 'no input data',
   'group': '',
   'isVisible': True}},
 'modulator': {'skipped_check': {'name': 'check skipped',
   'value_string': 'no channel data',
   'group': '',
   'isVisible': True}},
 'dni': {'gy': {'name': 'GY anomaly - Check that static surveys are ok in shop',
   'value': 60,
   'unit': '%',
   'limit': 60,
   'status': 'Warning',
   'group': '',
   'isVisible': True},
  'gz': {'name': 'GZ anomaly',
   'value': 55.38,
   'unit': '%',
   'limit': 60,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'min_shxyz': {'name': 'Min SHX, SHY, SHZ',
   'value': -39616,
   'unit': 'nT',
   'limit': -65000,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'max_shxyz': {'name': 'Max SHX, SHY, SHZ',
   'value': 35168,
   'unit': 'nT',
   'limit': 65000,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'total_h': {'name': 'total static H',
   'value': 57824,
   'unit': 'nT',
   'limit': 70000,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'h_anomaly': {'name': 'Magnetometer anomaly',
   'value': 0.6,
   'unit': '',
   'limit': 0.6,
   'status': 'Warning',
   'group': '',
   'isVisible': True},
  'h_warning': {'name': 'Notice',
   'value_string': 'if warning triggered,check tool is not in casing;if in casing,ignore warning',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '1.1',
   'group': '',
   'isVisible': True}},
 'ltb': {'avg_tt1': {'name': 'Array Resistivity Compensated 6&8": Avg Perc failure comms in 1 min',
   'value': 1.84,
   'unit': '%',
   'limit': 50,
   'status': 'Pass',
   'group': '',
   'isVisible': True},
  'max_tt1': {'name': 'Array Resistivity Compensated 6&8": Max Perc failure comms in 1 min',
   'value': 100,
   'unit': '%',
   'limit': 90,
   'status': 'Warning',
   'group': '',
   'isVisible': True},
  'address_t1': {'name': 'Position T1 Array Resistivity Compensated 6&8"',
   'value': 12,
   'unit': '',
   'group': '',
   'isVisible': True},
  'ltb': {'name': 'LTB health channels',
   'value': None,
   'unit': '',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '1.0',
   'group': '',
   'isVisible': True}},
 'downlink': {'check_skipped': {'name': 'check skipped',
   'value_string': 'no DLMSG data',
   'group': '',
   'isVisible': True}},
 'statuswords': {'rsrg_16_sum_hrs': {'name': 'RSRG Bit4 Time Activated Hours',
   'value': 0,
   'unit': 'hours',
   'group': '',
   'isVisible': True},
  'rsrg_16_sum_percentage': {'name': 'RSRG Bit4 Time Activated Percentage',
   'value': 0,
   'unit': '%',
   'group': '',
   'isVisible': True},
  'algorithm_version': {'name': 'Algorithm Version',
   'value_string': '2.0',
   'group': '',
   'isVisible': True},
  'status_summary': {'key': 'status_summary',
   'name': 'Status summary',
   'status': 'Pass',
   'table': [{'status_word': 'MWDSTAT', 'status': 'Pass'},
    {'status_word': 'LTB_STAT', 'status': 'Info'},
    {'status_word': 'CALSTE', 'status': 'Pass'},
    {'status_word': 'SENST', 'status': 'Pass'},
    {'status_word': 'PUPSTAT', 'status': 'Info'},
    {'status_word': 'PUP_STAT2', 'status': 'Pass'},
    {'status_word': 'MOT_STATUS', 'status': 'Pass'},
    {'status_word': 'MOT_DERR', 'status': 'Pass'},
    {'status_word': 'RSRG', 'status': 'Info'}],
   'isVisible': True},
  'status_details': {'key': 'status_details',
   'name': 'Status details',
   'table': [{'details': 'MWDSTAT BIT 0: MMA Jamming (%)',
     'limit': 4,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MWDSTAT BIT 1: MMA Oil Level (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MWDSTAT BIT 2: MTA Oil Status (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MWDSTAT BIT 3: Cal File Read (%)',
     'limit': 0.02,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MWDSTAT BIT 4: Temp Senor/ADC cal (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MWDSTAT BIT 5: VDC/TRPM ratio (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'LTB_STAT BIT 0: CDN Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 1: CDR Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 2: RAB Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 3: Sonic Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 4: ADN Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 5: ARC Retries (%)',
     'limit': 100,
     'value': 39.06,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 6: MR Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 7: SMWD Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 8: TST Retries (%)',
     'limit': 100,
     'value': 4.07,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 9: RCV Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 10: NBS Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 11: USC Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 12: RWOB Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 13: DVDM Retries (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'LTB_STAT BIT 14: Other Retries (%)',
     'limit': 100,
     'value': 4.9,
     'status': 'Info'},
    {'details': 'CALSTE BIT 0: Temps A/D Converter (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 1: HX A/D Converter (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 2: HY A/D Converter (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 3: HZ A/D Converter (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 4: TRQ A/D Converter (%)',
     'limit': 0.03,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 5: WOB A/D Converter (%)',
     'limit': 8,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 6: Stat Survey Retry (%)',
     'limit': 20,
     'value': 0.76,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 7: Primary ADC Switch (%)',
     'limit': 0.01,
     'value': 0,
     'status': 'Pass'},
    {'details': 'CALSTE BIT 8: -2V Ref (%)',
     'limit': 40,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 0: GZ (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 1: GY (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 2: GX (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 3: HZ (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 4: HY (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 5: HX (%)',
     'limit': 45,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 6: GZ Temperature (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 7: GY Temperature (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 8: GX Temperature (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 9: H Temperature (%)',
     'limit': 20,
     'value': 0,
     'status': 'Pass'},
    {'details': 'SENST BIT 10: Total G Magnitude (%)',
     'limit': 45,
     'value': 2.15,
     'status': 'Pass'},
    {'details': 'PUPSTAT BIT 2: DI Calib. Reading (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 3: RM Memory (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 4: Logging Memory (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 5: TPS Status (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 6: ROP Power (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 7: TF TYPE (%)',
     'limit': 100,
     'value': 23.62,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 8: On-Demand Frame (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 9: Rotating Flag (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 10: High Voltage (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 11: Configuration read (%)',
     'limit': 100,
     'value': 3.23,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 12: LTB mode (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 13: RTC battery connected (%)',
     'limit': 100,
     'value': 0,
     'status': 'Info'},
    {'details': 'PUPSTAT BIT 14: LTB Acquisition (%)',
     'limit': 100,
     'value': 0.12,
     'status': 'Info'},
    {'details': 'PUP_STAT2 BIT 0: MTR Queue Retry (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 1: MTR Config Retry (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 2: SYS Acq Que Send (%)',
     'limit': 3,
     'value': 0.18,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 3: LTB Scan Que Send (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 4: Get MTR Data Q Snd (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 5: Data Proc Que Send (%)',
     'limit': 3,
     'value': 1.26,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 6: Vib Data Proc Q Snd (%)',
     'limit': 3,
     'value': 0.18,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 7: LTB Cmpr Data Q Snd (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 8: Req Frm DP Que Send (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 9: Clr Rg Fr Buf Q Snd (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 10: Rec Mem Que Free (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 11: Mem Rec Req Q Send (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 12: Legacy Dlnk Q Send (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 13: AutoDlnk TRPM Q Snd (%)',
     'limit': 3,
     'value': 1.32,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 14: Fast Dlnk Frm Q Snd (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'PUP_STAT2 BIT 15: Sys Throughput (%)',
     'limit': 3,
     'value': 1.32,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 0: High Voltage Status (%)',
     'limit': 100,
     'value': 95.51,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 1: Motor Status (%)',
     'limit': 100,
     'value': 95.1,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 2: Duty Cycle (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 3: Low Voltage Status (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 11: Velocity (%)',
     'limit': 100,
     'value': 95.16,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 12: Hard Jam (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 13: Wiggle Activated (%)',
     'limit': 3,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 14: Jamming Indicator (%)',
     'limit': 3,
     'value': 2.81,
     'status': 'Pass'},
    {'details': 'MOT_STATUS BIT 15: MMA Oil Level (%)',
     'limit': 0.1,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 0: Program Stack Overflow (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 1: Program Stack Underflow (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 2: Program Checksum (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 3: Resolver Glitch (%)',
     'limit': 8,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 14: Motor Queue underflow (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},
    {'details': 'MOT_DERR BIT 15: Motor Queue overflow (%)',
     'limit': 100,
     'value': 0,
     'status': 'Pass'},

In [ ]:
tool = dict(data['equipment'][0])
fcsn =dict(filter(lambda x: x[0] == 'fcsn',tool.items()))

In [ ]:
config = data['configuration']
config

{'code': 'PUP',
 'version': 'PUPV14.0C04',
 'build': '',
 'revision': '',
 'dumpTime': 'Tue, 07 Jan 2020 00:54:09 GMT',
 'type': None,
 'collarSize': None,
 'collarSizeUnit': None,
 'dumpTimeTicks': None,
 'useManufacturingCodeForEquipmentMatching': False,
 'toolName': 'TeleScope',
 'toolTypeName': '',
 'job': {'name': '19MED0040',
  'company': 'BORR DRILLING',
  'wellName': 'MULACH 5',
  'fieldName': 'MULACH',
  'county': 'PARAISO',
  'state': 'TABASCO',
  'location': 'MXM',
  'engineer': 'MYusoff',
  'initTime': 'Sat, 21 Dec 2019 17:07:53 GMT',
  'tsVersion': '2019.0.01.131',
  'toolSerialNumber': '3274'},
 'configurationFile': None,
 'toolSerial': 3274,
 'coefficients': {'telem': 3,
  'freq_bps': [6, 0, 0, 28, 0, 0, 0, 0],
  'cur_fsl_no': 0,
  'auto_survey_time': 0,
  'pause_period_time': 276,
  'conn_threshold': 0,
  'g_max': 10003,
  'g_min': 9953,
  'h_max': 13364,
  'h_min': 13164,
  'dip_max': 7352,
  'dip_min': 7245,
  'soc_switch': 0,
  'survey_only': 0,
  'gtf_switch_low': 250,
  'gtf_switch_high': 350,
  'option_control_iab_enable': 0,
  'option_control_delayed_survey': 1,
  'option_control_record_struct': 0,
  'option_control_frame_struct': 0,
  'option_control_rotary_switch': 0,
  'option_control_sleep_mode': 0,
  'option_control_soc_algo': 1,
  'option_control_shk_type': 0,
  'option_control_medium_survey': 0,
  'option_control_rep_crc': 0,
  'option_control_dc_soc': 0,
  'option_control_survey_count': 0,
  'mult_shot': 0,
  'rm_primary': 29,
  'rm_alt1': 0,
  'rm_alt2': 0,
  'fsl_alt1': 0,
  'fsl_alt2': 0,
  'telem_alt1': 0,
  'telem_alt2': 0,
  'freq_alt1': 0,
  'freq_alt2': 0,
  'nbits_sync1': 9,
  'pattern_sync1': 59,
  'nbits_sync2': 9,
  'pattern_sync2': 452,
  'freq_sync2': 0,
  'nbits_presync': 0,
  'pattern_presync': 0,
  'nbits_presync_cpmsk': 9,
  'pattern_presync_cpmsk': 59,
  'nbits_presync_bpsk': 9,
  'pattern_presync_bpsk': 59,
  'nbits_presync_qpsk': 24,
  'pattern_presync_qpsk': 490166,
  'xmitter_power': 0,
  'tool_main_address': 152,
  'collar_rpm': 20,
  'dlk_bit_time': 18,
  'e_dlk_personality': 0,
  'dspa_soc': 0,
  'total_modf_in_all_sets': 1,
  'modf_frames': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'modf_frames_set': [0, 0, 0, 0, 0],
  'bha_power_sharing_control': 0,
  'downlink_select_tst_pom_tstx': 0,
  'survey_wait': 0,
  'delayed_survey_wait': 5,
  'health_modf_status': 2,
  'dds_interval': 255,
  'modulator_disabled': 255,
  'collar_id': 255,
  'disable_gamma_dtc': 255,
  'disable_ltb_communication': 255,
  'disable_ltb_power_uphole': 255,
  'disable_ltb_power_downhole': 255}}

In [ ]:
runs =data['runs'][0]
run = dict(filter(lambda x:  x[0] == 'runNumber',runs.items() ))
run

{'runNumber': '19MED0040-2'}

In [ ]:
data['headers']

{'tool': 'TeleScope',
 'type': '',
 'code': 'PUP',
 'initTime': '2019-12-21T17:07:53.000Z',
 'dumpTime': '2020-01-07T00:54:09.000Z',
 'version': '2022.1.0',
 'name': 'pmea-3274-jobdump-6nero2020.bin',
 'path': 'C:\\PUP Dumps',
 'partitions': ['pmea-3274-jobdump-6nero2020.bin'],
 'uploadedOn': '2022-04-13T16:45:51.565Z',
 'uploadedBy': 'etirado2@slb.com',
 'timestamp': 1649868351556}

In [ ]:
data['results'].keys()

dict_keys(['runinfo', 'general', 'environmental', 'manual', 'modulator', 'dni', 'ltb', 'downlink', 'statuswords', 'PHM_MDB', 'techlog', 'analysis', 'overall_status'])

In [ ]:
environmental =data['results']['environmental']
environmental
env ={key: value.get('value') for key, value in environmental.items()}
env

{'shk50_g': 155,
 'sh_krisk3': 0,
 'shk_temp': 0,
 'sns_100_100': 0.7455555555555556,
 'sns_100_150': 0.3388888888888889,
 'sns_100200_75': 0,
 'sns_100200_125': 0,
 'sns_200_50': 0,
 'sns_200_100': 0,
 'vibx_m': 0,
 'viby_m': 0,
 'vibz_m': 0,
 'vibl_m': 0.16666666666666666,
 'vibx_h': 0,
 'viby_h': 0,
 'vibz_h': 0,
 'vibl_h': 0,
 'peakshock': 112,
 'shk25': 1618,
 'shk50': 154,
 'shk125': 1,
 'shk250': 0,
 'action_table': None,
 'algorithm_version': None}

In [ ]:
temp = ['max_hstemp','max_hstemp','hstemp_130','hstemp_150','hstemp_175']
newDict = dict(filter(lambda x: x[0] in temp,data['results']['general'].items()))
tempvalues ={k:v['value'] for (k,v) in newDict.items()}

In [ ]:
tooldict = {**fcsn, **tempvalues, **env,**run, **toolset_dict}

In [ ]:
tooldict

{'fcsn': 'PMEA-CA.3274',
 'max_hstemp': 47,
 'hstemp_130': 0,
 'hstemp_150': 0,
 'hstemp_175': 0,
 'shk50_g': 155,
 'sh_krisk3': 0,
 'shk_temp': 0,
 'sns_100_100': 0.7455555555555556,
 'sns_100_150': 0.3388888888888889,
 'sns_100200_75': 0,
 'sns_100200_125': 0,
 'sns_200_50': 0,
 'sns_200_100': 0,
 'vibx_m': 0,
 'viby_m': 0,
 'vibz_m': 0,
 'vibl_m': 0.16666666666666666,
 'vibx_h': 0,
 'viby_h': 0,
 'vibz_h': 0,
 'vibl_h': 0,
 'peakshock': 112,
 'shk25': 1618,
 'shk50': 154,
 'shk125': 1,
 'shk250': 0,
 'action_table': None,
 'algorithm_version': None,
 'runNumber': '19MED0040-2',
 'toolset': [{'fcsn': 'S-262553.225_TEMP',
   'description': 'M10-MVC ACCEL BLOCK ASSEMBLY',
   'toolsetLevel': 3},
  {'fcsn': 'S-262642.4019',
   'description': 'ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10',
   'toolsetLevel': 3},
  {'fcsn': 'S-270540.152334-1',
   'description': 'ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT',
   'toolsetLevel': 3},
  {'fcsn': 'S-270570.152106-3',
   'description': 'ASSEMBLY, M10 MOTOR CONTROL',
   'toolsetLevel': 3},
  {'fcsn': 'S-270640.151642-5',
   'description': 'ASSEMBLY, M10 ACQUISITION',
   'toolsetLevel': 3},
  {'fcsn': 'S-270780.191478-2',
   'description': 'ASSEMBLY, D&I CALIBRATION',
   'toolsetLevel': 3},
  {'fcsn': 'S-270910.116233-3',
   'description': 'ASSEMBLY, PWB, VIBRATION ACQUISITION',
   'toolsetLevel': 3},
  {'fcsn': 'S-271007.1110-7',
   'description': 'ASSEMBLY, TRIPLE TRANSFORMER',
   'toolsetLevel': 3},
  {'fcsn': '100162589.151502-5',
   'description': 'ASSEMBLY, TRIPLE POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100515238.151276-1',
   'description': 'PWA, TEL101, LTB POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100515238.151276-4',
   'description': 'PWA, TEL101, LTB POWER SUPPLY',
   'toolsetLevel': 3},
  {'fcsn': '100522201.151286-3',
   'description': 'PWA, TEL102, MOTOR DRIVE',
   'toolsetLevel': 3},
  {'fcsn': '100543577.5785410010',
   'description': 'PWA, TEL103, WDDHC05',
   'toolsetLevel': 3}]}

In [ ]:
df =pd.DataFrame(tooldict)

In [ ]:
df

,fcsn,max_hstemp,hstemp_130,hstemp_150,hstemp_175,shk50_g,sh_krisk3,shk_temp,sns_100_100,sns_100_150,...,vibl_h,peakshock,shk25,shk50,shk125,shk250,action_table,algorithm_version,runNumber,toolset
0,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-262553.225_TEMP', 'description': '..."
1,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-262642.4019', 'description': 'ELEC..."
2,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270540.152334-1', 'description': '..."
3,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270570.152106-3', 'description': '..."
4,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270640.151642-5', 'description': '..."
5,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270780.191478-2', 'description': '..."
6,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270910.116233-3', 'description': '..."
7,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-271007.1110-7', 'description': 'AS..."
8,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': '100162589.151502-5', 'description': ..."
9,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': '100515238.151276-1', 'description': ..."
10,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': '100515238.151276-4', 'description': ..."
11,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': '100522201.151286-3', 'description': ..."
12,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,0,112,1618,154,1,0,None,None,19MED0040-2,"{'fcsn': '100543577.5785410010', 'description'..."

In [ ]:
df[['Component','Description', 'level']] =df['toolset'].apply(pd.Series)

In [ ]:
df

,fcsn,max_hstemp,hstemp_130,hstemp_150,hstemp_175,shk50_g,sh_krisk3,shk_temp,sns_100_100,sns_100_150,...,shk50,shk125,shk250,action_table,algorithm_version,runNumber,toolset,Component,Description,level
0,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-262553.225_TEMP', 'description': '...",S-262553.225_TEMP,M10-MVC ACCEL BLOCK ASSEMBLY,3
1,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-262642.4019', 'description': 'ELEC...",S-262642.4019,"ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10",3
2,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270540.152334-1', 'description': '...",S-270540.152334-1,"ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT",3
3,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270570.152106-3', 'description': '...",S-270570.152106-3,"ASSEMBLY, M10 MOTOR CONTROL",3
4,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270640.151642-5', 'description': '...",S-270640.151642-5,"ASSEMBLY, M10 ACQUISITION",3
5,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270780.191478-2', 'description': '...",S-270780.191478-2,"ASSEMBLY, D&I CALIBRATION",3
6,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-270910.116233-3', 'description': '...",S-270910.116233-3,"ASSEMBLY, PWB, VIBRATION ACQUISITION",3
7,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': 'S-271007.1110-7', 'description': 'AS...",S-271007.1110-7,"ASSEMBLY, TRIPLE TRANSFORMER",3
8,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': '100162589.151502-5', 'description': ...",100162589.151502-5,"ASSEMBLY, TRIPLE POWER SUPPLY",3
9,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': '100515238.151276-1', 'description': ...",100515238.151276-1,"PWA, TEL101, LTB POWER SUPPLY",3
10,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': '100515238.151276-4', 'description': ...",100515238.151276-4,"PWA, TEL101, LTB POWER SUPPLY",3
11,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': '100522201.151286-3', 'description': ...",100522201.151286-3,"PWA, TEL102, MOTOR DRIVE",3
12,PMEA-CA.3274,47,0,0,0,155,0,0,0.745556,0.338889,...,154,1,0,None,None,19MED0040-2,"{'fcsn': '100543577.5785410010', 'description'...",100543577.5785410010,"PWA, TEL103, WDDHC05",3

In [ ]:
from genericpath import isfile

def get_boards_data(folder):
  files = os.listdir(folder)

  dataframes=[]

  for file in files:
    full_path = os.path.join(folder,file)
    if os.path.isfile(full_path):

      try:

        f = open(full_path)
        data =json.load(f)
        #Run Number
        runs =data['runs'][0]
        run = dict(filter(lambda x:  x[0] == 'runNumber',runs.items() ))

        #Tool Info
        tool = dict(data['equipment'][0])
        fcsn =dict(filter(lambda x: x[0] == 'fcsn',tool.items()))

        #environmental conditions
        environmental =data['results']['environmental']
        env ={key: value.get('value') for key, value in environmental.items()}

        #Temperature exposure
        temp = ['max_hstemp','max_hstemp','hstemp_130','hstemp_150','hstemp_175']
        newDict = dict(filter(lambda x: x[0] in temp,data['results']['general'].items()))
        tempvalues ={k:v['value'] for (k,v) in newDict.items()}


        #Toolset composition
        toolset =data['toolset']
        toolset= [{'fcsn':d['fcsn'],'description': d['description'],'toolsetLevel':d['toolsetLevel'] }for d in toolset if d.get('component') in ['TeleScope PWA','PowerPulse/TeleScope']]
        toolset_dict = {
          'toolset':toolset
            }
        #Final Dictionary
        tooldict = {**fcsn, **tempvalues, **env,**run, **toolset_dict}
        df =pd.DataFrame(tooldict)
        df[['Component','Description', 'level']] =df['toolset'].apply(pd.Series)
        dataframes.append(df)
      except:
        pass
  return dataframes

In [ ]:
df =get_boards_data('/content/drive/MyDrive/Colab Notebooks/Proyecto de innovacion/Analytics Results/Results')

In [ ]:
pd.concat(df ).reset_index()

,index,fcsn,max_hstemp,hstemp_130,hstemp_150,hstemp_175,shk50_g,sh_krisk3,shk_temp,sns_100_100,...,shk125,shk250,action_table,algorithm_version,runNumber,toolset,Component,Description,level,value_error
0,0,PMEA-CA.3274,47,0.0,0.0,0.0,155.0,0.0,0.0,0.745556,...,1.0,0.0,None,None,19MED0040-2,"{'fcsn': 'S-262553.225_TEMP', 'description': '...",S-262553.225_TEMP,M10-MVC ACCEL BLOCK ASSEMBLY,3,NaN
1,1,PMEA-CA.3274,47,0.0,0.0,0.0,155.0,0.0,0.0,0.745556,...,1.0,0.0,None,None,19MED0040-2,"{'fcsn': 'S-262642.4019', 'description': 'ELEC...",S-262642.4019,"ELECTRONIC ASSEMBLY, MAGNETOMETER, SEXTANT, M10",3,NaN
2,2,PMEA-CA.3274,47,0.0,0.0,0.0,155.0,0.0,0.0,0.745556,...,1.0,0.0,None,None,19MED0040-2,"{'fcsn': 'S-270540.152334-1', 'description': '...",S-270540.152334-1,"ASSEMBLY, DYNAMIC OVERRANGE CIRCUIT",3,NaN
3,3,PMEA-CA.3274,47,0.0,0.0,0.0,155.0,0.0,0.0,0.745556,...,1.0,0.0,None,None,19MED0040-2,"{'fcsn': 'S-270570.152106-3', 'description': '...",S-270570.152106-3,"ASSEMBLY, M10 MOTOR CONTROL",3,NaN
4,4,PMEA-CA.3274,47,0.0,0.0,0.0,155.0,0.0,0.0,0.745556,...,1.0,0.0,None,None,19MED0040-2,"{'fcsn': 'S-270640.151642-5', 'description': '...",S-270640.151642-5,"ASSEMBLY, M10 ACQUISITION",3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753,9,PMEA-CA.5175,110,0.0,0.0,0.0,245.0,0.0,0.0,1.592778,...,6.0,0.0,None,None,O.1008285.02-13,"{'fcsn': '100515238.311908-5', 'description': ...",100515238.311908-5,"PWA, TEL101, LTB POWER SUPPLY",4,NaN
2754,10,PMEA-CA.5175,110,0.0,0.0,0.0,245.0,0.0,0.0,1.592778,...,6.0,0.0,None,None,O.1008285.02-13,"{'fcsn': '100515238.311915-5', 'description': ...",100515238.311915-5,"PWA, TEL101, LTB POWER SUPPLY",4,NaN
2755,11,PMEA-CA.5175,110,0.0,0.0,0.0,245.0,0.0,0.0,1.592778,...,6.0,0.0,None,None,O.1008285.02-13,"{'fcsn': '100522201.01425010', 'description': ...",100522201.01425010,"PWA, TEL102, MOTOR DRIVE",4,NaN
2756,12,PMEA-CA.5175,110,0.0,0.0,0.0,245.0,0.0,0.0,1.592778,...,6.0,0.0,None,None,O.1008285.02-13,"{'fcsn': '100543577.310684-4', 'description': ...",100543577.310684-4,"PWA, TEL103, WDDHC05",4,NaN
2757,13,PMEA-CA.5175,110,0.0,0.0,0.0,245.0,0.0,0.0,1.592778,...,6.0,0.0,None,None,O.1008285.02-13,"{'fcsn': '100927677.310677-21', 'description':...",100927677.310677-21,"PWA, PROTECTION BOARD",4,NaN